CREATE ROLE admin_user WITH LOGIN PASSWORD 'admin_EPSI@2024';
CREATE ROLE readonly_user WITH LOGIN PASSWORD 'readonly_EPSI@2024';
CREATE ROLE readwrite_user WITH LOGIN PASSWORD 'readwrite_EPSI@2024';

GRANT ALL PRIVILEGES ON DATABASE seahawks_db TO admin_user;

GRANT CONNECT ON DATABASE seahawks_db TO readonly_user;
GRANT USAGE ON SCHEMA public TO readonly_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly_user;

GRANT CONNECT ON DATABASE seahawks_db TO readwrite_user;
GRANT USAGE ON SCHEMA public TO readwrite_user;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO readwrite_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO readwrite_user;